import "ViewModels.idl";

namespace gui
{
    [default_interface]
    runtimeclass DashboardPage : Microsoft.UI.Xaml.Controls.Page
    {
        DashboardPage();

        gui.ViewModels.DashboardPageViewModel ViewModel{get;};
    }
}
