namespace gui.Models{
    enum MapperStatus {stop = 0, running, error};
    enum Simulators {none = 0, fs2020, dcs};
    enum MessageType {error = 0, warning, info, message, debug, events};

    runtimeclass Device {
        Device(String cname, String dname);

        String ClassName{get;};
        String DeviceName{get;};
    }

    runtimeclass MappingsStat{
        MappingsStat();

        Int32 Primery;
        Int32 Secondary;
        Int32 Viewports;
        Int32 Views;
    }

    runtimeclass View {
        View(Int32 id, String name);

        Int32 Id{get;};
        String Name{get;};
    }

    runtimeclass Viewport {
        Viewport(String name, Object views);

        String Name{get;};
        Windows.Foundation.Collections.IVector<View> Views{get;};
    }

    runtimeclass CapturedWindow : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        CapturedWindow(Object mapper, UInt32 cwid, String name, String description, String targetClass, Windows.Foundation.Collections.IVector<String> targetTitles);

        UInt32 Cwid{get;};
        String Name{get;};
        String Description{get;};
        String StatusString{get;};
        String TargetClass{get;};
        Windows.Foundation.Collections.IVector<String> TargetTitles{get;};
        Boolean IsCaptured{get;};
        Boolean IsNotCaptured{get;};
        Microsoft.UI.Xaml.Media.ImageSource Image{get;};
        Microsoft.UI.Xaml.Style ButtonStyle{get;};
        Boolean ButtonIsEnabled{get;};

        Windows.Foundation.IAsyncAction ToggleCapture(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void CaptureWindow(UInt64 hwnd);
        void ForceRelease();
    }

    runtimeclass Message {
        Message(MessageType type, String text);

        MessageType Type{get;};
        Microsoft.UI.Xaml.Style TextStyle{get;};
        String TypeString{get;};
        String Text{get;};
    }

    runtimeclass Mapper: Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        Mapper();

        String ScriptPath;
        MapperStatus Status{get;};
        Simulators ActiveSim{get;};
        String AircraftName{get;};
        Boolean ViewportIsActive{get;};
        Windows.Foundation.Collections.IVector<Viewport> Viewports{get;};
        Windows.Foundation.Collections.IObservableVector<CapturedWindow> CapturedWindows{get;};
        Windows.Foundation.Collections.IVector<Device> Devices{get;};
        MappingsStat MappingsInfo{get;};
        Windows.Foundation.Collections.IObservableVector<Message> Messages{get;};
        Boolean EventMessageIsEnabled;
        Boolean DebugMessageIsEnabled;
        Boolean IsAvailableNewRelease{get;};
        String LatestRelease{get;};
        Boolean IsIgnoredUpdate;

        Microsoft.UI.Xaml.Media.ImageSource NullWindowImage{get;};

        void RunScript();
        void StopScript();
        void StopScriptSync();

        void CaptureWindow(UInt32 Cwid, UInt64 hWnd);
        void ReleaseWindow(UInt32 Cwid);
        Boolean StartViewports();
        Boolean StopViewports();

        void CaptureWindowBypassingGUI(UInt32 Cwid, UInt64 hWnd);
        void StartViewportsIfReady();

        void DownloadLatestRelease();
    }
}