namespace gui.Models{
    enum MapperStatus {stop = 0, running, error};
    enum Simulators {none = 0, fs2020, dcs};

    runtimeclass Device {
        Device(String cname, String dname);

        String ClassName{get;};
        String DeviceName{get;};
    }

    runtimeclass Mapper: Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        Mapper();

        String ScriptPath;
        MapperStatus Status{get;};
        Simulators ActiveSim{get;};
        String AircraftName{get;};
        Windows.Foundation.Collections.IObservableVector<Device> Devices{get;};

        void RunScript();
        void StopScript();
    }
}