import "Models.idl";

namespace gui.ViewModels{
    runtimeclass MainWindowViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        MainWindowViewModel();

        String ScriptName{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush ScriptStatusBrush{get;};
        Boolean OpenButtonIsEnabled{get;};
        Boolean StartStopButtonIsEnabled{get;};
        String StartStopButtonIcon{get;};
        String StartStopButtonLabel{get;};

        Windows.Foundation.IAsyncAction ClickOpenButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickStartStopButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }

    runtimeclass DashboardPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        DashboardPageViewModel();

        gui.Models.Mapper Mapper{get;};
        Boolean NormalViewIsVisible{get;};
        Boolean StopViewIsVisible{get;};
        Boolean ErrorViewIsVisible{get;};
        Boolean SimIconIsVisible{get;};
        Microsoft.UI.Xaml.Media.Imaging.BitmapImage SimIconSource{get;};
        String SimString{get;};
        String DeviceSummary{get;};
        String DeviceDetail{get;};
        Boolean DeviceDetailIsVisible{get;};
        String MappingsSummary{get;};
        Int32 MappingsDetailPrimery{get;};
        Int32 MappingsDetailSecondary{get;};
        Int32 MappingsDetailViewports{get;};
        Int32 MappingsDetailViews{get;};
        Boolean MappingsDetailIsVisible{get;};
        String ViewportSummary{get;};
        String ViewportDetail{get;};
        Boolean ViewportDetailIsVisible{get;};
        Boolean ViewportButtonIsEnabled{get;};
        Boolean ViewportButtonIsVisible{get;};
        String ViewportButtonText{get;};
        Boolean CapturedWindowsIsVisible{get;};
        String CapturedWindowsSummary{get;};
        Boolean CaptureWindowButtonIsEnabled{get;};

        Windows.Foundation.IAsyncAction ToggleViewport(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }

    runtimeclass ConsolePageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        ConsolePageViewModel();

        gui.Models.Mapper Mapper{get;};
        void EraseLog(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }

    runtimeclass SettingsPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        SettingsPageViewModel();

        Boolean RunScriptOnStartup;
        Int32 MessageLogSize;
        String PreRunScript;
        Boolean PreRunScriptIsVarid;
        Int32 RenderingMethod;
        Int32 PluginFolderType;
        String DefaultPluginPath{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush DefaultPluginPathColor{get;};
        String UserSpecifiedPluginPath{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush UserSpecifiedPluginPathColor{get;};
        Boolean ChangePluginPathButtonIsValid{get;};

        Windows.Foundation.IAsyncAction ClickChangePluginPathButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}
