import "Models.idl";

namespace gui.ViewModels{
    runtimeclass MainWindowViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        MainWindowViewModel();

        String ScriptName{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush ScriptStatusBrush{get;};
        Boolean OpenButtonIsEnabled{get;};
        Boolean StartStopButtonIsEnabled{get;};
        String StartStopButtonIcon{get;};
        String StartStopButtonLabel{get;};
        String StartStopButtonToolTip{get;};
        Boolean NewReleaseNotificationIsNecessary{get;};
        String LatestVersion{get;};

        Windows.Foundation.IAsyncAction ClickOpenButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickStartStopButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void GuideMenu_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void SiteMenu_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void GithubMenu_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ReleaseMenu_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickCloseNewReleaseButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickDownloadNewReleaseButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        Windows.Foundation.IAsyncAction RestartScript(String path);
    }

    runtimeclass DashboardPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        DashboardPageViewModel();

        gui.Models.Mapper Mapper{get;};
        Boolean NormalViewIsVisible{get;};
        Boolean StopViewIsVisible{get;};
        Boolean ErrorViewIsVisible{get;};
        Boolean SimIconIsVisible{get;};
        Single SimIconHeight{get;};
        Microsoft.UI.Xaml.Media.Imaging.BitmapImage SimIconSource{get;};
        String SimString{get;};
        Boolean AircraftNameIsVisible{get;};
        String AircraftName{get;};
        String DeviceSummary{get;};
        String DeviceDetail{get;};
        Boolean DeviceDetailIsVisible{get;};
        String MappingsSummary{get;};
        Int32 MappingsDetailPrimery{get;};
        Int32 MappingsDetailSecondary{get;};
        Int32 MappingsDetailViewports{get;};
        Int32 MappingsDetailViews{get;};
        Boolean MappingsDetailIsVisible{get;};
        String ViewportSummary{get;};
        String ViewportDetail{get;};
        Boolean ViewportDetailIsVisible{get;};
        Boolean ViewportButtonIsEnabled{get;};
        Boolean ViewportButtonIsVisible{get;};
        String ViewportButtonText{get;};
        Boolean CapturedWindowsIsVisible{get;};
        String CapturedWindowsSummary{get;};
        Boolean CaptureWindowButtonIsEnabled{get;};
        Microsoft.UI.Xaml.Style StartStopViewportsButtonStyle{get;};

        Windows.Foundation.IAsyncAction ToggleViewport(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }

    runtimeclass ConsolePageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        ConsolePageViewModel();

        gui.Models.Mapper Mapper{get;};
        void EraseLog(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }

    runtimeclass SettingsPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
        SettingsPageViewModel();

        Boolean RunScriptOnStartup;
        Int32 MessageLogSize;
        Boolean DeveloperLog;
        Boolean LuaLibBaseIsEnable;
        Boolean LuaLibCoroutineIsEnable;
        Boolean LuaLibDebugIsEnable;
        Boolean LuaLibIoIsEnable;
        Boolean LuaLibMathIsEnable;
        Boolean LuaLibOsIsEnable;
        Boolean LuaLibPackageIsEnable;
        Boolean LuaLibStringIsEnable;
        Boolean LuaLibTableIsEnable;
        Boolean LuaLibUtf8IsEnable;
        String PreRunScript;
        Boolean PreRunScriptIsValid;
        Int32 RenderingMethod;
        Boolean UseSeparatedUIThread;
        Int32 PluginFolderType;
        String PluginPath{get;};
        String DefaultPluginPath{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush DefaultPluginPathColor{get;};
        String UserSpecifiedPluginPath{get;};
        Microsoft.UI.Xaml.Media.SolidColorBrush UserSpecifiedPluginPathColor{get;};
        Boolean ChangePluginPathButtonIsValid{get;};
        String Version{get;};
        String Copyright{get;};
        String Commit{get;};
        String CommitUrl{get;};
        Boolean NewReleaseAvailable{get;};
        String NewRelease{get;};
        Boolean DcsIsInstalled{get;};
        Boolean DcsExporterIsEnabled;
        Boolean TouchMouseEmulationIsEnable;
        Boolean TouchDelayMouseEmulation;
        Int32 TouchDownDelay;
        Int32 TouchUpDelay;
        Int32 TouchDragStartDelay;
        Boolean TouchDoubleTapOnDrag;
        Int32 TouchDeadzoneForDrag;
        Int32 TouchPointerJitter;
        Int32 TouchMoveTriggerDistance;
        Int32 TouchMinimumInterval;

        Windows.Foundation.IAsyncAction ClickChangePluginPathButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickResetTouchConfig(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ClickDownloadNewReleaseButton(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}
