namespace gui.Dialogs{
    runtimeclass WindowItem : Microsoft.UI.Xaml.Data.INotifyPropertyChanged{
        WindowItem(UInt64 hwnd, String name);

        UInt64 hWnd{get;};
        String Name{get;};
        Microsoft.UI.Xaml.Media.ImageSource Image;
    }

    runtimeclass WindowPickerViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged{
        WindowPickerViewModel();

        WindowItem SelectedItem{get;};
        Windows.Foundation.Collections.IObservableVector<WindowItem> WindowItems{get;};

        Windows.Foundation.IAsyncOperation<WindowItem> PickWindowAsync();
    }
}