local utils = require('fsmapper_utils')
local fmt = utils.struct('c1I3:4c1I3S2')
local s = fmt:pack('V', 'Z', 123, 'opiopan')
print(''..s:len())
print(''..s:byte(2))
local v1, v2, v3, v4 = fmt:unpack(s)
print(v1..':'..v2..':'..v3..':'..v4)
